### PR TITLE
Johnfreeman/issue29 local markdown files

### LINKED ISSUE #29: Support localized Markdown files
For some packages, developer work is organically resulting in Markdown files appearing in non-`docs/` subdirectories. E.g., for `daq-systemtest`, some of the subdirectories for specific tests contain `README.md`s which describe the test in question. While this coupling can be useful for developers and testers, right now there's not a mechanism in `the_final_markdown.sh` to incorporate this kind of Markdown file; rather, all Markdown files must appear in the `docs/` subdirectory. It would be nice to have such a mechanism.

### PR DESCRIPTION
**Pull request by jcfreeman2**

### CODE REVIEW

**Comment by jcfreeman2** [comment]
This PR means that Markdown files outside of a package's `docs/` subdirectory get added to a package's table of contents in the official documentation (and of course can be linked to from the main `README.md` page). If you look at https://dune-daq-sw.readthedocs.io/en/johnfreeman-issue29_local_markdown_files/ you can see, e.g., how the schema instructions inside of `appfwk`'s `schema/` subdirectory get added.

**Review by dingp — COMMENTED** [review]
One comment about handling the symbolic links in another subdirectory than `docs`, for example `src/README.md`.

Looks like the current solution is to create `pkg/src_README.md` in `docs` repo. However, this solution has one drawback. If the original package's `docs/README.md` or even other pages in a different sub-directory contains a link to `src/README.md`, that link will be broken on readthedocs website.

One solution is to fix the links when copying the markdown file to `docs` repo. But that may require some careful checking/replacing of strings.

Another solution is, use subdirectories in `docs/pkg` repo, such as `docs/pkg/src/README.md`. And in the source repo, create symbolic links under its `docs` subdirectory to any other subdirectories containing any markdown files. This way, the links to other pages can remain the same in both the pkg repo and docs repo.

**Comment by jcfreeman2** [comment]
@dingp based on your suggestion, I've switched to a model whereby the local path of Markdown files outside of `docs/` gets recreated within `docs/`. You can see how this works in https://dune-daq-sw.readthedocs.io/en/johnfreeman-issue29_local_markdown_files/ ; particularly helpful might be looking at the daq-systemtest documentation on the page.

**Comment by dingp** [comment]
That looks good to me. Only thing remaining is to create the symbolic links to other subdirectories under `daq-systemtest/docs`, so the link like [this one](https://github.com/DUNE-DAQ/daq-systemtest/blob/johnfreeman/issue24_update_doc_structure/docs/config/hd_coldbox_tests/README.md) renders correctly on GitHub.

Edit: we should let people know that those symlinks under `pkg/docs` to other subdirs is a responsibility of package developers, and only needed if they used the relative links in markdown files, and care about rendering the links on GitHub.

**Review by dingp — APPROVED** [review]
LGTM

**Pull request merged**
